database:
  enabled: false
  jdbc-url: "jdbc:mysql://localhost:3306/economylimit?useSSL=false&autoReconnect=true"
  jdbc-class: "com.mysql.cj.jdbc.Driver"
  properties:
    user: root
    password: 123456

daily-reset:
  time-zone: "Asia/Shanghai"
  reset-time:
    hour: 0
    minute: 0
    second: 0
  period-time: 20
  auto-save: false

vanilla-exp:
  enabled: true
  limits:
    default: 100
    vip: 200
    mvp: 300
  bypass-permission: "economylimit.bypass"

vanilla-levels:
  enabled: true
  limits:
    default: 100
    vip: 200
    mvp: 300
  bypass-permission: "economylimit.bypass"

messages:
  error-args: "&#98FB98[EconomyLimit] &cWrong command usage, if you need help, use /economylimit help!"
  error-only-in-game: "&#98FB98[EconomyLimit] &cYou have to use this command in game!"
  error-miss-permission: "&#98FB98[EconomyLimit] &cYou don't have permission to use this command!"
  error-player-not-found: "&#98FB98[EconomyLimit] &cPlayer is not found!"
  reseted: "&#98FB98[EconomyLimit] &aReseted the player date!"
  reloaded: "&#98FB98[EconomyLimit] &aPlugin reloaded!"
  help:
    main: |
      &#98FB98&lEconomyLimit &7Made by @PQguanfang
      &f/economylimit help &7- View help.
    main-admin: |
      &#98FB98&lEconomyLimit &7Made by @PQguanfang
      &f/economylimit reset <playerName> &7- Reset specified player data.
      &f/economylimit reload &7- Reload the plugin.
    main-console: |
      &#98FB98&lEconomyLimit &7Made by @PQguanfang
      &f/economylimit reset <playerName> &7- Reset specified player data.
      &f/economylimit reload &7- Reload the plugin.
