database:
  # If you want to use SQLLite, please replace this option to:
  # jdbc:sqlite:%plugin_folder%/data.db
  jdbc-url: 'jdbc:mysql://localhost:3306/economylimit?useSSL=false&autoReconnect=true'
  # If you are using old Minecraft version server, please replace this option to:
  # com.mysql.jdbc.Driver
  # If you want to use SQLLite, please replace this option to:
  # org.sqlite.JDBC
  jdbc-class: 'com.mysql.cj.jdbc.Driver'
  # If you want to use SQLLite, set enabled option to false.
  properties:
    enabled: true
    user: root
    password: 123456

vanilla-exp:
  enabled: true
  limits:
    default: 100
    vip: 200
    mvp: 300
  bypass-permission: "economylimit.bypass"

vanilla-levels:
  enabled: true
  limits:
    default: 100
    vip: 200
    mvp: 300
  bypass-permission: "economylimit.bypass"

messages:
  error-args: "&#98FB98[EconomyLimit] &cWrong command usage, if you need help, use /economylimit help!"
  error-only-in-game: "&#98FB98[EconomyLimit] &cYou have to use this command in game!"
  error-miss-permission: "&#98FB98[EconomyLimit] &cYou don't have permission to use this command!"
  error-player-not-found: "&#98FB98[EconomyLimit] &cPlayer is not found!"
  reseted: "&#98FB98[EconomyLimit] &aReseted the player date!"
